server:
    port: 8080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: default
        url: jdbc:postgresql://localhost:5432/users
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                temp:
                    use_jdbc_metadata_defaults: false
        show-sql: true
    kafka:
        bootstrap-servers: localhost:9092
